--- 
- hosts: Linux 
  roles: 
    - {role: Linux_android-sdk, become: yes}

- hosts: windows
  roles:
    - {role: Windows_android-sdk, become: yes}

- hosts: MAC
  roles:
    - {role: MAC_android-sdk, become: yes}
